--
-- Each TRUNCATE in copydb.sh names several of these tables.
-- Every table gets 10 rows, so a sequence that was not restarted is at 10.
--
create table parent (id bigint generated by default as identity primary key, v text);
create table child (id serial primary key, parent_id bigint references parent(id), v text);

create table tr3 (id serial primary key, v text);
create table tr5 (id serial primary key, v text);

-- quotes, a comma, a space and a keyword: the name must stay one relation
create schema "S p";
create table "S p"."T, ONLY x" (id serial primary key, v text);

create table casc_parent (id serial primary key, v text);
create table casc_child (id serial primary key, parent_id int references casc_parent(id), v text);

create table tr6 (id serial primary key, v text);
create table tr7 (id serial primary key, v text);
create table excl (id serial primary key, v text);

-- target.sql turns flat into a partitioned table on the target
create table flat (id int primary key, v text);

create table kept (id serial primary key, v text);

insert into parent(v) select 'seed' from generate_series(1, 10);
insert into child(parent_id, v) select g, 'seed' from generate_series(1, 10) g;
insert into tr3(v) select 'seed' from generate_series(1, 10);
insert into tr5(v) select 'seed' from generate_series(1, 10);
insert into "S p"."T, ONLY x"(v) select 'seed' from generate_series(1, 10);
insert into casc_parent(v) select 'seed' from generate_series(1, 10);
insert into casc_child(parent_id, v) select g, 'seed' from generate_series(1, 10) g;
insert into tr6(v) select 'seed' from generate_series(1, 10);
insert into tr7(v) select 'seed' from generate_series(1, 10);
insert into excl(v) select 'seed' from generate_series(1, 10);
insert into flat select g, 'seed' from generate_series(1, 10) g;
insert into kept(v) select 'seed' from generate_series(1, 10);
